<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Persistence\DataAccess\Configurations\" />
    <Folder Include="Persistence\Migrations\" />
    <Folder Include="Persistence\Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookingService.Application\BookingService.Application.csproj" />
    <ProjectReference Include="..\BookingService.Domain\BookingService.Domain.csproj" />
  </ItemGroup>

</Project>
