using EventApp.Shared.Authentication;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi;
using OpenTelemetry.Exporter;
using OpenTelemetry.Logs;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;
using System.Reflection;
using System.Text.Json;
using UserService.App.Middleware;
using UserService.Application.Abstractions.Persistence.Repositories;
using UserService.Application.Abstractions.Services;
using UserService.Infrastructure.Persistence.DataAccess;
using UserService.Infrastructure.Persistence.Kafka;
using UserService.Infrastructure.Persistence.Repositories;

var builder = WebApplication.CreateBuilder(args);
AuthenticationComponent.AddAuthentication(builder);
builder.Services.AddAuthorization();
// Add services to the container.

builder.Services.AddControllers();
builder.Services.AddControllersWithViews()
    .AddNewtonsoftJson(options =>
    options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
);
builder.Logging.AddJsonConsole(options =>
{
    options.JsonWriterOptions = new JsonWriterOptions
    {
        Indented = false
    };
});
var serviceName = builder.Configuration.GetValue<string>("ServiceName")
                ?? throw new InvalidOperationException("ServiceName not found.");

builder.Services
    .AddOpenTelemetry()
    .ConfigureResource(resource => resource
        .AddService(
            serviceName: serviceName))
    .WithMetrics(metrics =>
    {
        metrics
            .AddAspNetCoreInstrumentation()
            .AddRuntimeInstrumentation()
            .AddPrometheusExporter();
    })
    .WithTracing(tracing => tracing
        .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService(serviceName))
        .AddAspNetCoreInstrumentation(options =>
        {
            options.Filter = httpContext =>
            {
                var path = httpContext.Request.Path;

                return !path.StartsWithSegments("/health") &&
                       !path.StartsWithSegments("/metrics");
            };
        })
        .AddHttpClientInstrumentation()
        .AddEntityFrameworkCoreInstrumentation()
        .AddOtlpExporter(options =>
        {
            var otlpExporterEndpoint = builder.Configuration.GetValue<string>("OtlpExporterEndpoint")
                ?? throw new InvalidOperationException("OtlpExporterEndpoint not found.");
            options.Endpoint = new Uri(otlpExporterEndpoint);

            options.Protocol = OtlpExportProtocol.HttpProtobuf;

            options.BatchExportProcessorOptions.ScheduledDelayMilliseconds = 1000;

            options.BatchExportProcessorOptions.ExporterTimeoutMilliseconds = 5000;
        }))
    .WithLogging(logging => logging
        .AddOtlpExporter());

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
                ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");
builder.Services.AddOpenApi();
builder.Services.AddDbContext<UserDbContext>(options =>
    options.UseNpgsql(connectionString));
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
builder.Services.AddSingleton<KafkaProducerService>(provider =>
{
    var bootstrapServers = builder.Configuration.GetValue<string>("Kafka:BootstrapServers")
                ?? throw new InvalidOperationException("Kafka string 'BootstrapServers' not found.");
    return new KafkaProducerService(bootstrapServers);
});

builder.Services.AddScoped<IUserRepository, UserRepository>();
builder.Services.AddScoped<IUserService, UserService.Application.Services.UserService>();

builder.Services.AddSwaggerGen(options =>
{
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    options.IncludeXmlComments(xmlPath);

    // Add a Security Scheme (using a JWT Bearer token).
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "Bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Please enter token"
    });

    // Add a Security Requirement (without this, even if you set 
    // the JWT in the Authorize window, Swagger will not include
    // Authorization: Bearer ... in the request header).
    // In the code below, `document` is the OpenAPI document 
    // generated by SwaggerGen. Add a Security Requirement to 
    // that document.
    options.AddSecurityRequirement(document =>
        new OpenApiSecurityRequirement
        {
            [new OpenApiSecuritySchemeReference("Bearer", document)] = []
        });
});
builder.Services.AddProblemDetails();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<UserDbContext>();
    db.Database.Migrate();

}
app.UseMiddleware<GlobalExceptionHandlingMiddleware>();
// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
    app.MapOpenApi();
}

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.MapPrometheusScrapingEndpoint();
app.MapControllers();

app.Run();
